spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=1.0
spring.ai.openai.chat.options.max-completion-tokens=1000

#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=llama3.1:8b
#qwen3.5:4b llama3.1:8b

#weather.api.key=${OPENWEATHER_API_KEY}
weather.api.key=28b7a71596649508f0c34106d6c3aa7f
weather.api.base-url=http://api.openweathermap.org/data/2.5/weather


