spring.application.name=gmail-mcp-server1

# port setting
server.port=8081

##### Gmail SMTP setting
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=myksphone2001@gmail.com
spring.mail.password=uznjksyxklponwol
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

##### MCP Server setting
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.name=gmail-mcp-server1
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.protocol=STREAMABLE


#Spring AI 로그 출력 설정
logging.level.org.springframework.ai=DEBUG

#Spring Boot Actuator 엔드포인트 공개 설정
management.endpoints.web.exposure.include=*