spring.application.name=step02_LoginForm

#user setting
#spring.security.user.name=kosta
#spring.security.user.password=1234
#spring.security.user.roles=USER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Seoul
spring.datasource.username=jang
spring.datasource.password=jang1234

# 하이버네이트가 자동으로 가장 적합한 MySQL 버전을 찾도록 세팅
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ddl-auto와 show-sql을 제어하는 가장 확실한 옵션 조합
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=tru