spring.application.name=step01

# OpenAI API
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini

# gemini
#spring.ai.google.genai.api-key=AQ.Ab8RN6JpDfvjpwcWh1yVYPGbfk32zbjjkRPsOmJA6_X8Gc_MDA
#spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# ollama
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=llama3:latest