spring:
  application:
    name: springai10

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: jang
    password: 1234
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        table-name : hotel_vector
        initialize-schema: true